apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-agent-config
  namespace: appdynamics
data:
  APPDYNAMICS_CONTROLLER_HOST_NAME: controller-4517nosshco-ixoarnbx.appd-cx.com
  APPDYNAMICS_CONTROLLER_PORT: "8090" 
  EVENT_ENDPOINT: "http://controller-4517nosshco-ixoarnbx.appd-cx.com:9080"
  APPDYNAMICS_CONTROLLER_SSL_ENABLED: "false"
  APPDYNAMICS_AGENT_ACCOUNT_NAME: customer1
  APPDYNAMICS_AGENT_GLOBAL_ACCOUNT_NAME: customer1_b9005dda-07af-4393-a1d3-e5a005af3870

